version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "deps"
    prefix-development: "deps(dev)"
- package-ecosystem: 'npm'
  directory: '/examples/'
  schedule:
    interval: 'daily'
  ignore:
    - dependency-name: "@ipld/car"
  commit-message:
    prefix: 'chore'
    include: 'scope'
